// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/signup": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/signup";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/_auth.login.tsx": {
    id: "routes/_auth.login";
    page: "/login";
  };
  "routes/_auth.signup.tsx": {
    id: "routes/_auth.signup";
    page: "/signup";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/_auth.login": typeof import("./app/routes/_auth.login.tsx");
  "routes/_auth.signup": typeof import("./app/routes/_auth.signup.tsx");
};